create type public.agent_board_status as enum ('backlog', 'ready', 'in_progress', 'done');

alter table public.agent_tasks
add column if not exists board_status public.agent_board_status not null default 'ready',
add column if not exists board_order numeric not null default 0,
add column if not exists board_updated_at timestamptz not null default now();

create index if not exists agent_tasks_agent_board_idx
  on public.agent_tasks (agent_id, board_status, board_order, updated_at desc);

create table if not exists public.code_sessions (
  id uuid primary key default gen_random_uuid(),
  agent_id uuid not null references public.agents(id) on delete cascade,
  status text not null default 'active',
  created_by uuid not null references public.profiles(id) on delete restrict,
  started_at timestamptz not null default now(),
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint code_sessions_status_valid check (status in ('active', 'idle', 'closed', 'error'))
);

create trigger set_code_sessions_updated_at
before update on public.code_sessions
for each row execute function public.set_updated_at();

create index if not exists code_sessions_agent_started_idx
  on public.code_sessions (agent_id, started_at desc);

create table if not exists public.code_session_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.code_sessions(id) on delete cascade,
  seq bigint not null,
  direction text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint code_session_events_direction_valid check (direction in ('input', 'output', 'system')),
  unique (session_id, seq)
);

create index if not exists code_session_events_session_seq_idx
  on public.code_session_events (session_id, seq);

create table if not exists public.agent_workspace_snapshots (
  id uuid primary key default gen_random_uuid(),
  agent_id uuid not null references public.agents(id) on delete cascade,
  snapshot_version bigint not null,
  tree_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (agent_id, snapshot_version)
);

create index if not exists agent_workspace_snapshots_agent_created_idx
  on public.agent_workspace_snapshots (agent_id, created_at desc);

create table if not exists public.agent_workspace_files (
  id bigint generated by default as identity primary key,
  snapshot_id uuid not null references public.agent_workspace_snapshots(id) on delete cascade,
  path text not null,
  content text,
  content_hash text,
  size integer,
  language text,
  updated_at timestamptz not null default now(),
  unique (snapshot_id, path)
);

create index if not exists agent_workspace_files_snapshot_path_idx
  on public.agent_workspace_files (snapshot_id, path);

alter table public.code_sessions enable row level security;
alter table public.code_session_events enable row level security;
alter table public.agent_workspace_snapshots enable row level security;
alter table public.agent_workspace_files enable row level security;

create policy "code_sessions_read_authenticated"
on public.code_sessions
for select
using (auth.role() = 'authenticated');

create policy "code_session_events_read_authenticated"
on public.code_session_events
for select
using (auth.role() = 'authenticated');

create policy "agent_workspace_snapshots_read_authenticated"
on public.agent_workspace_snapshots
for select
using (auth.role() = 'authenticated');

create policy "agent_workspace_files_read_authenticated"
on public.agent_workspace_files
for select
using (auth.role() = 'authenticated');

create policy "code_sessions_write_operator_admin"
on public.code_sessions
for all
using (public.current_app_role() in ('operator', 'admin'))
with check (public.current_app_role() in ('operator', 'admin'));

create policy "code_session_events_write_operator_admin"
on public.code_session_events
for all
using (public.current_app_role() in ('operator', 'admin'))
with check (public.current_app_role() in ('operator', 'admin'));

create policy "agent_workspace_snapshots_write_operator_admin"
on public.agent_workspace_snapshots
for all
using (public.current_app_role() in ('operator', 'admin'))
with check (public.current_app_role() in ('operator', 'admin'));

create policy "agent_workspace_files_write_operator_admin"
on public.agent_workspace_files
for all
using (public.current_app_role() in ('operator', 'admin'))
with check (public.current_app_role() in ('operator', 'admin'));
